In [12]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

clf.predict([[0, 6], [1, 2], [2, 0]])

array([1, 1, 0])

In [13]:
?tree.DecisionTreeClassifier()

In [44]:
import pandas as pd
from sklearn.tree import  DecisionTreeClassifier
filename = './机器学习周志华_西瓜数据集.xlsx'
data = pd.read_excel(filename, index_col=0)
data.head()

色泽  根蒂  敲声  纹理  脐部  触感 好瓜
编号                           
1   青绿  蜷缩  浊响  清晰  凹陷  硬滑  是
2   乌黑  蜷缩  沉闷  清晰  凹陷  硬滑  是
3   乌黑  蜷缩  浊响  清晰  凹陷  硬滑  是
4   青绿  蜷缩  沉闷  清晰  凹陷  硬滑  是
5   浅白  蜷缩  浊响  清晰  凹陷  硬滑  是

In [54]:
data_dict = {'乌黑':3, '青绿':2, '浅白':1, '硬挺':3, '稍蜷':2, '蜷缩':1, }
data.iloc[0]
for i, j in range():
    
    

色泽    青绿
根蒂    蜷缩
敲声    浊响
纹理    清晰
脐部    凹陷
触感    硬滑
好瓜     是
Name: 1, dtype: object

In [2]:
import numpy as np
scores = np.array([89, 81, 71, 78, 32, 53, 100, 98, 49])
print(scores[ scores > 60 ].mean())

86.16666666666667


In [4]:
a = 1
b = a
a += b
b

1

In [6]:
a = [1, 2, 3]
b = a
a += [1, 1, 1]
b

[1, 2, 3, 1, 1, 1]

In [9]:
a = np.array([1, 2, 3])
b = a
a += 1
print(a)
print()
print(b)

[2 3 4]

[2 3 4]


In [11]:

a = np.array([1, 2, 3])

b = a

a = a + np.array([1,1,1])

print(b)    

[1 2 3]


In [12]:

a = np.array([1, 2, 3])

b = a

a += np.array([1,1,1])

print(b)    

[2 3 4]


In [14]:
a = np.array([1, 2, 3, 4])

b = a[:2]

b[0] = -10

print(a)
print(b)

[-10   2   3   4]
[-10   2]


# 数学公式

$f(x)$ 

$\dfrac{\partial f(x,\ y)}{\partial x}= lim_{\Delta x \rightarrow 0} \dfrac{f(x+ \Delta x,\ y) - f(x,\ y)}{\Delta x}$   

$\dfrac{\partial f(x,\ y)}{\partial y} = \displaystyle\lim_{\Delta y \rightarrow 0} \dfrac{f(x,\ y + \Delta y) - f(x,\ y)}{\Delta y}$ 